name: pr_check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      name: Build
      run: cargo build
      name: Run 
      run: cargo test --verbose 
